title: Designerd
url: "https://designerd.site"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://designerd.site"
footer_text: "Copyright 2020 © Designerd </ br>Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Portfolio"
   link: "/Portfolio/"
 - name: "Contact"
   link: "contact"
